### ISSUE TITLE
crash after encoding finishes

### ISSUE THREAD

**Issue by wbolster** [ZivaVatra/flac2all#44]
hi, thanks for this useful tool.

i have a problem though: after encoding is finished, `flac2all` (installed from the pypi release using `pipx install`) always crashes. this is the traceback:

```
UTC~21:31:24: Processing Complete!
UTC~21:31:24: Waiting for all running process to complete.
UTC~21:31:24: Processing run log...
Traceback (most recent call last):
  File "/home/wbolster/.local/bin/flac2all", line 8, in <module>
    sys.exit(main())
  File "/home/wbolster/.local/pipx/venvs/flac2all/lib/python3.8/site-packages/flac2all_pkg/__init__.py", line 440, in main
    threaded_encode()
  File "/home/wbolster/.local/pipx/venvs/flac2all/lib/python3.8/site-packages/flac2all_pkg/multiprocess_encode.py", line 188, in encode
    failures = generate_summary(start_time, end_time, len(files), result_log, opts['outdir'])
TypeError: generate_summary() takes 4 positional arguments but 5 were given
```

**Comment by wbolster** [comment]
after i drop the 5 argument completely from that call, it still crashes, with this backtrace:

```
UTC~21:35:57: Processing run log...
Traceback (most recent call last):
  File "/home/wbolster/.local/bin/flac2all", line 8, in <module>
    sys.exit(main())
  File "/home/wbolster/.local/pipx/venvs/flac2all/lib/python3.8/site-packages/flac2all_pkg/__init__.py", line 440, in main
    threaded_encode()
  File "/home/wbolster/.local/pipx/venvs/flac2all/lib/python3.8/site-packages/flac2all_pkg/multiprocess_encode.py", line 188, in encode
    failures = generate_summary(start_time, end_time, len(files), result_log)
  File "/home/wbolster/.local/pipx/venvs/flac2all/lib/python3.8/site-packages/flac2all_pkg/core.py", line 154, in generate_summary
    num1 = execT[int((len(execT) - 1) / 2) - 1]
IndexError: list index out of range
```

**Comment by ZivaVatra** [comment]
Hi Wbolster,

Glad you like it! Can you give me the exact command line you run? That way I can try to replicate the bug.

Thanks!

**Comment by ZivaVatra** [comment]
Ok, I managed to trigger this bug while working on issue #45 . This should be fixed in the current version 5 branch. Please check out and test.

**Comment by wbolster** [comment]
thanks for having a look and fixing the issue :+1:

(tbh, `flac2all` didn't fit my use case after all, and i switched to a simpler hand-written approach to create vorbis ‘mirrors’ of my flac sources.)

**Comment by ZivaVatra** [comment]
No worries, always important to use the right tool for the job :-) 
Will close ticket now.
