### ISSUE TITLE
Ubuntu 18.04 - not sure what's up?

### ISSUE THREAD

**Issue by MangoCats** [ZivaVatra/flac2all#46]
I'm having a rough time getting anything going with flac2all in Ubuntu 18.04.

I have albums of .flac files made by whipper, I have setup a python3 venv to run flac2all in, I'm trying to transcode to mp3 with the command: `flac2all mp3 --lame-options='v b 192' .
`, but I get the following results, and I'm not sure where to go from here:

```
(flac2all_env) mike@NUC7i5Upstairs:~/output/album/R.E.M. - Automatic for the People$ flac2all mp3 --lame-options='v b 192' .
UTC~15:29:09: We have 12 flac files to convert
UTC~15:29:09: We have 0 non-flac files to copy across
UTC~15:29:09: Spawning execution process
UTC~15:29:09: Spawning execution process
UTC~15:29:09: Processing: 	02. R.E.M. - Try Not to Breathe.flac      target: mp3      
UTC~15:29:09: Spawning execution process
UTC~15:29:09: Processing: 	06. R.E.M. - Sweetness Follows.flac       target: mp3      
UTC~15:29:09: Spawning execution process
UTC~15:29:09: Processing: 	03. R.E.M. - The Sidewinder Sleeps Tonite.flac  target: mp3      
UTC~15:29:09: Processing: 	10. R.E.M. - Man on the Moon.flac         target: mp3      
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'



Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'

UTC~15:29:20: Spawning execution process
UTC~15:29:20: Spawning execution process
UTC~15:29:20: Spawning execution process
UTC~15:29:20: Spawning execution process
UTC~15:29:20: Processing: 	08. R.E.M. - Ignoreland.flac              target: mp3      
UTC~15:29:20: Processing: 	12. R.E.M. - Find the River.flac          target: mp3      
UTC~15:29:20: Processing: 	04. R.E.M. - Everybody Hurts.flac         target: mp3      
UTC~15:29:20: Processing: 	07. R.E.M. - Monty Got a Raw Deal.flac    target: mp3      
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'

Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'


Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'

UTC~15:29:30: Spawning execution process
UTC~15:29:30: Spawning execution process
UTC~15:29:30: Spawning execution process
UTC~15:29:30: Spawning execution process
UTC~15:29:30: Processing: 	11. R.E.M. - Nightswimming.flac           target: mp3      
UTC~15:29:30: Processing: 	09. R.E.M. - Star Me Kitten.flac          target: mp3      
UTC~15:29:30: Processing: 	05. R.E.M. - New Orleans Instrumental No. 1.flac  target: mp3      
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'
UTC~15:29:30: Processing: 	01. R.E.M. - Drive.flac                   target: mp3      

Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'

Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 402, in run
    self.logq.put(self.encode(infile, mode, self.opts), timeout=10)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/core.py", line 287, in encode
    return encf(infile, outfile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/mp3.py", line 88, in convert
    inmetadata = flac().getflacmeta(infile)
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/flac.py", line 98, in getflacmeta
    flacfile
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'metaflac': 'metaflac'


UTC~15:29:41: Process queue finished.
UTC~15:29:51: Processing Complete!
UTC~15:29:51: Waiting for all running process to complete.
UTC~15:29:51: Processing run log...
Traceback (most recent call last):
  File "/home/mike/environments/flac2all_env/bin/flac2all", line 11, in <module>
    sys.exit(main())
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/__init__.py", line 440, in main
    threaded_encode()
  File "/home/mike/environments/flac2all_env/lib/python3.6/site-packages/flac2all_pkg/multiprocess_encode.py", line 188, in encode
    failures = generate_summary(start_time, end_time, len(files), result_log, opts['outdir'])
TypeError: generate_summary() takes 4 positional arguments but 5 were given
(flac2all_env) mike@NUC7i5Upstairs:~/output/album/R.E.M. - Automatic for the People$
```

**Comment by MangoCats** [comment]
Fixed with `sudo apt install flac`  whipper is running from a docker instance, threw me off.

**Comment by MangoCats** [comment]
Perhaps a premature closing: no longer crashing, but it seems to be hung with no output other than creating an empty mp3 folder - no cpu usage, but not returning either:

```
flac2all mp3 --lame-options='v b 192' .
UTC~15:44:13: We have 12 flac files to convert
UTC~15:44:13: We have 0 non-flac files to copy across
UTC~15:44:13: Spawning execution process
UTC~15:44:13: Spawning execution process
UTC~15:44:13: Spawning execution process
UTC~15:44:13: Spawning execution process
UTC~15:44:13: Processing: 	02. R.E.M. - Try Not to Breathe.flac      target: mp3      
UTC~15:44:13: Processing: 	06. R.E.M. - Sweetness Follows.flac       target: mp3      
UTC~15:44:13: Processing: 	03. R.E.M. - The Sidewinder Sleeps Tonite.flac  target: mp3      
UTC~15:44:13: Processing: 	10. R.E.M. - Man on the Moon.flac         target: mp3      
Warning: No Genre detected, setting to "Unknown"
Warning: No Genre detected, setting to "Unknown"
Warning: No Genre detected, setting to "Unknown"
Warning: No Genre detected, setting to "Unknown"
lame: excess arg /tmp/flac2all_3faca392-992d-476f-a436-4cbd1b84da4b-31ca189e-293b-4c47-b1e7-acd49036a05b
lame: excess arg /tmp/flac2all_b89e0516-ad89-4d10-a294-3dbf9f55b5be-409e87c1-b426-4e69-b80b-e149743e8772
lame: excess arg /tmp/flac2all_4af80f98-8282-448b-9d11-d12454fd7988-c9c360d9-8280-43f4-95ad-a154f4db6988
lame: excess arg /tmp/flac2all_587ca535-1d75-4dce-84f0-a026e745eeca-726a39d1-437b-4b5c-a985-8e6a339fb915
```
???

**Comment by ZivaVatra** [comment]
What are the command lines of lame? 

On linux, you should be able to paste the output of "ps -ef | grep lame"

**Comment by ZivaVatra** [comment]
Actually, having a closer look at your original command, you are setting the lameopts wrong. You wrote this:

> flac2all mp3 --lame-options='v b 192' 

However lame-options are colon delimited, as shown in the help output. Quoted here:

>  --lame-options=LAMEOPTS
>                         Options to pass to lame,for example:
>                         '-preset extreme:q 0:h:-abr'. Any lameoption can be
>                         specified here, if you want a short option (e.g.
>                         -h),then just do 'h'. If you want a long option (e.g.
>                         '--abr'), then you needa dash: '-abr'

Try again first without lame-options, to just make sure everything works. After you can try adding the options.

If you still have issues, feel free to re-open the ticket.

**Comment by MangoCats** [comment]
Thanks, I missed the : delimited trick - that would explain it.

lame was exiting too quickly for me to get a look at the reconstituted
command line options.
