### ISSUE TITLE
multiprocess_encode() calls generate_summary() in core with wrong number of arguments

### ISSUE THREAD

**Issue by socketbox** [ZivaVatra/flac2all#48]
```
UTC~01:41:29: Processing Complete!                                         
UTC~01:41:29: Waiting for all running process to complete.                  
UTC~01:41:29: Processing run log...                                               
Traceback (most recent call last):                                                
  File "/home/user/.pyenv/versions/3-8-3/bin/flac2all", line 11, in <module>       
    load_entry_point('flac2all==5.1', 'console_scripts', 'flac2all')()            
  File "/home/user/.pyenv/versions/3.8.3/envs/3-8-3/lib/python3.8/site-packages/flac2all-5.1-py3.8.egg/flac2all_pkg/__init__.py", line 440, in main
    threaded_encode()                                                                                         
  File "/home/user/.pyenv/versions/3.8.3/envs/3-8-3/lib/python3.8/site-packages/flac2all-5.1-py3.8.egg/flac2all_pkg/multiprocess_encode.py", line 188, in encod
e                                                                                                                   
    failures = generate_summary(start_time, end_time, len(files), result_log, opts['outdir'])                       
TypeError: generate_summary() takes 4 positional arguments but 5 were given                                         

```
Command executed was `flac2all mp3 -t 8 -o ./mp3_tracks ./`

**Comment by hermlon** [comment]
I also stumbled across this, but just realized it's already been fixed in the version5 branch for a while https://github.com/ZivaVatra/flac2all/commit/a7d367928c9e22b3bc2d27359b64de5d169d7e75

(Not related to this issue: at least for me the version5 branch was missing two import statements, therefore I opened this pull request https://github.com/ZivaVatra/flac2all/pull/49)

**Comment by ZivaVatra** [comment]
Yes, it has been fixed, just got a lot of other fixes I want to merge into the next version5 release. Thanks for the pull request, that should be merged now as well!
