### ISSUE TITLE
The `encode_thread` API after Python 3.9

### ISSUE THREAD

**Issue by robfrawley** [ZivaVatra/flac2all#67]
Due to API change, the following issue is experienced on Python versions after `3.9` (the method `isAlive` was renamed to `is_alive`):

```
Traceback (most recent call last):
  File "/home/rmf/bin/flac2all", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/robfr/Projects/flac2all-venv/lib/python3.10/site-packages/flac2all_pkg/__init__.py", line 440, in main
    threaded_encode()
  File "/mnt/c/Users/robfr/Projects/flac2all-venv/lib/python3.10/site-packages/flac2all_pkg/multiprocess_encode.py", line 157, in encode
    ap = [x for x in ap if x.isAlive()]
  File "/mnt/c/Users/robfr/Projects/flac2all-venv/lib/python3.10/site-packages/flac2all_pkg/multiprocess_encode.py", line 157, in <listcomp>
    ap = [x for x in ap if x.isAlive()]
AttributeError: 'encode_thread' object has no attribute 'isAlive'. Did you mean: 'is_alive'?
```

**Comment by ZivaVatra** [comment]
Thanks for letting me know, python3.9 is not something I've upgraded to yet. Have to see if there is some way to accommodate this without breaking compatibility with python <3.9.

**Comment by ZivaVatra** [comment]
hmm, actually I just checked, I am running python3.11, quite a bit after version 3.9. 
Have you tested the version5 branch of flac2all? Your issue may already be solved there. A quick grep shows the code is using "is_alive" there, so this may already be fixed, it just needs to be bundled into a new release.

**Comment by frank-topel-dbi** [comment]
So what does this mean? Will the current version of flac2all work with recent Python versions?

**Comment by ZivaVatra** [comment]
It means the issue was fixed in the version5 branch, but it has not yet been merged into master or packaged into a release.

I wanted some confirmation from the original ticket raiser that it works for them before I merged to  master in case there was some edge case  that was missed while testing on my system.

Can you check out the version5 branch of flac2all and confirm if it works ok for you?

**Comment by 0n-s** [comment]
Not OP, but I can attest that in the version5 branch this bug is indeed fixed on current Python.

**Comment by ambroisie** [comment]
I've hit this on NixOS with the 5.1 release.

I noticed that `version5`'s README mentions a 5.3 release: could you please tag your releases @ZivaVatra? It looks like 5.2 and 5.3 were not tagged, hence I fear some packagers missed them (like on nixpkgs).

**Comment by ZivaVatra** [comment]
@ambroisie Thanks for letting me know. I will have to see why there has been no further tagging.
@0n-s : Great, thanks for confirming, I think we are good to close this ticket off as complete now.
